---
title: "analisis_paralaje"
author: "JMason88"
date: "29 de octubre de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r limpieza memoria}
rm(list=ls())
```



```{r pressure}
library(tidyr)
library(readxl)

```

```{r}

hip <- read.csv("./02.Preprocesamiento/hip_version1.csv")
tyc <- read_xlsx("./00.Datos_y_TP/hyades_source.xlsx", sheet = "Tycho")

tyc_aux <- read.csv("./02.Preprocesamiento/tyc_version1.csv") %>% select(c(1,10))

tyc <- tyc %>% left_join(., tyc_aux, by = "recno")
tyc[is.na(tyc$Symbad_Hyades), "Symbad_Hyades"] <- FALSE

rm(tyc_aux)
summary(tyc)
```

```{r}
sapply(tyc, function(x) sum(is.na(x)))
 

```

```{r}

sapply(tyc %>% filter(!is.na(HD) & !is.na(HIP)), 
       function(x) sum(is.na(x)))


```

```{r}
sapply(tyc %>% 
         filter(!is.na(HD) & !is.na(HIP)) %>% 
         left_join(., hip[,c(1,4)], by = "HIP", suffix = c(".Tyc", ".Hip")),
       function(x) sum(is.na(x)))


```

```{r}

```

```{r}

```

