---
title: "Seleccion Final de Candidatas"
author: "Fernando Menendez"
date: "October 28, 2018"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(UpSetR)
library(dplyr)
library(ggplot2)
library(ggthemes)
```


```{r}
pam<-read.csv("hip_pamk5_clust.csv") %>% filter(Symbad_Hyades==F)
dbs<-read.csv("DBSCAN - Candidatas.csv")
fzy<-read.csv("FUZZY - Candidatas.csv")
```

```{r,include=FALSE}
dbs$X<-NULL
fzy$X<-NULL
dbs$source<-"DBSCAN"
fzy$source<-"FUZZY"
pam$source<-"PAM"
```

```{r}
cand.list<- dbs %>% rbind(fzy) %>% rbind(pam[,c("HIP","source")])
cand.list$source<-as.factor(cand.list$source)
ggplot(data=cand.list,aes(x=source)) +
  geom_bar(aes(fill=source)) +
  geom_text(stat='count',aes(label=..count..),vjust=1.6,color="white") +
  scale_fill_manual(name="Método",values=c("maroon","orange","blue")) +
  xlab("") +
  ylab("Estrellas") +
  theme_tufte()
```

```{r}
listInput<-list(DBSCAN=dbs$HIP,FUZZY=fzy$HIP,PAM=pam$HIP)
upset(fromList(listInput), order.by = "freq",point.size = 4, line.size = 2, 
    mainbar.y.label = "Interseccion de Candidastas", sets.x.label = "Método",
    sets.bar.color=c("blue","orange","maroon"))
```


__OBS:__ Como podemos ver en el grafico anterior, las estrellas detectadas en DBSCAN se encuentran tanto en PAM como en clustering difuso. Los 3 metodos comparten un total de __80__ estrellas, entendemos a partir de esta validacion que estas tienen mayor chance de pertenecer efectivamante al grupo de Hyades.

```{r}
cand.list.hip<- pam %>% select(HIP)
write.csv(cand.list.hip, "Candidatas Hyades - Hipparcos.csv",row.names = F)
cand.list.tyc<-read.csv("tyc_pam_clustk2.csv") %>% select(recno)
write.csv(cand.list.tyc, "Candidatas Hyades - Tycho.csv", row.names = F)
```

